baseURL: https://akhun.co/
title: A'Khun
theme: sam
hasCJKLanguage: true

params:
  footerText: 盒仔內 ê 時間
  mainMenu:
    - link: /notes
      text: notes
    - link: /posts
      text: posts
    - link: /about
      text: about
