baseURL: https://akhun.co/
title: A'Khun
theme: sam
hasCJKLanguage: true

params:
  profile:
    avatar: avatar.jpg
    info:
      - Singer / Coder
      - Taiwan
  homepage: home
  footerText: 盒仔內 ê 時間
  mainMenu:
    - link: /notes
      text: notes
    - link: /posts
      text: posts
    - link: /about
      text: about
  custom_css:
    - css/profile.css
